#!/usr/bin/env python3
"""
generate_default_version_variable_seed.py

Generates idempotent seed SQL for the default_version_variable table,
derived from default_versions_config.py -- so the seed data and the
config module can't drift apart from hand-editing two copies of the
same list.

Usage:
    python3 generate_default_version_variable_seed.py > seed_default_version_variable.sql

Uses INSERT ... ON CONFLICT (name) DO UPDATE, so it's safe to re-run
after re-syncing default_versions_config.py against the real upstream
file -- existing rows get their shape/active/last_synced_at updated
in place, new variables get inserted, and nothing needs to be deleted
by hand first.

Note: this does NOT delete rows for variables that have since been
removed from default_versions_config.py (e.g. if a *_DEFAULT var is
retired upstream). That's a deliberate choice -- silently dropping a
row could cascade if other tables ever reference it by id. Handle
removals as an explicit, reviewed step, not an automatic side effect
of reseeding.
"""

from __future__ import annotations

from default_versions_config import all_variable_records


def sql_escape(value: str) -> str:
    """Minimal single-quote escaping for a SQL string literal."""
    return value.replace("'", "''")


def generate_seed_sql() -> str:
    records = all_variable_records()

    lines = [
        "-- Generated by generate_default_version_variable_seed.py",
        "-- from default_versions_config.py -- do not hand-edit the",
        "-- data here; edit the config module and regenerate instead.",
        "",
        "BEGIN;",
        "",
    ]

    for r in records:
        name = sql_escape(r.name)
        shape = sql_escape(r.shape)
        active = "true" if r.active else "false"
        lines.append(
            "INSERT INTO default_version_variable (name, shape, active, last_synced_at)\n"
            f"VALUES ('{name}', '{shape}', {active}, now())\n"
            "ON CONFLICT (name) DO UPDATE\n"
            "SET shape = EXCLUDED.shape,\n"
            "    active = EXCLUDED.active,\n"
            "    last_synced_at = now();"
        )
        lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines)


if __name__ == "__main__":
    print(generate_seed_sql())
