-- Generated by generate_default_version_variable_seed.py
-- from default_versions_config.py -- do not hand-edit the
-- data here; edit the config module and regenerate instead.

BEGIN;

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('APACHE_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('BDB_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('COROSYNC_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('EBUR128_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('EMACS_DEFAULT', 'simple', false, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('FIREBIRD_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('FORTRAN_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('FPC_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('GCC_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('GHOSTSCRIPT_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('GL_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('GO_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('GUILE_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('IMAGEMAGICK_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('JAVA_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LAZARUS_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LIBRSVG2_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LINUX_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LLVM_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LUA_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('LUAJIT_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('MONO_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('MYSQL_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('NINJA_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('NODEJS_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('OPENLDAP_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PERL5_DEFAULT', 'complex', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PGSQL_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PHP_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PYCRYPTOGRAPHY_DEFAULT', 'conditional', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PYTHON_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('PYTHON2_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('RUBY_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('RUST_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('SAMBA_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('SSL_DEFAULT', 'complex', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('SUDO_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('TCLTK_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

INSERT INTO default_version_variable (name, shape, active, last_synced_at)
VALUES ('VARNISH_DEFAULT', 'simple', true, now())
ON CONFLICT (name) DO UPDATE
SET shape = EXCLUDED.shape,
    active = EXCLUDED.active,
    last_synced_at = now();

COMMIT;
